CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL,
    ip CHAR(15) DEFAULT NULL,
    delay INTEGER unsigned DEFAULT NULL,
    name TINYTEXT,
    message MEDIUMTEXT,
    bottag TINYINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    channel VARCHAR(100) NOT NULL,
    publicid BOOLEAN NOT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(40) NOT NULL
);

INSERT INTO user VALUES (1, 'Testuser', SHA1(CONCAT('Testuser', '1234')));
