CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	date DATETIME NOT NULL,
	ip CHAR(15) DEFAULT NULL,
	delay INTEGER unsigned DEFAULT NULL,
	name TINYTEXT,
	message MEDIUMTEXT,
	bottag TINYINT NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	channel VARCHAR(100) NOT NULL,
	publicid BOOLEAN NOT NULL
) DEFAULT CHARSET=utf8mb4;
